version: "3.8"  # Переконайтесь, що використовуєте актуальну версію

services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/usr/src/app
    command: npx nodemon -L --inspect=0.0.0.0 app.js --host 0.0.0.0 -p 3000 -c cache
